// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyiqtuwrlopbhyetazkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aXF0dXdybG9wYmh5ZXRhemt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5NTUzMDgsImV4cCI6MjA5NTUzMTMwOH0.jPs-pBkAnr_VKHJ3ZGD-y7nWXVZ4oREObr0c8nodbD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});